services:
  sisgea-module-autenticacao:
    image: node:18
    user: node
    command: sh -c "tail -f /dev/null"
    container_name: sisgea-module-autenticacao
    working_dir: /code
    depends_on:
      - sisgea-module-autenticacao-db
    networks:
      - sisgea-net
    ports:
      - 127.128.30.13:3013:3013
      - 127.128.30.13:9229:9229
    volumes:
      - ../../:/code
    env_file:
      - .env

  sisgea-module-autenticacao-db:
    image: bitnami/postgresql:15
    container_name: sisgea-module-autenticacao-db
    volumes:
      - 'sisgea-module-autenticacao-db-data:/bitnami/postgresql'
    networks:
      - sisgea-net
    ports:
      - 127.128.30.13:5432:5432
    env_file:
      - .db.env

networks:
  sisgea-net:
    external: true

volumes:
  sisgea-module-autenticacao-db-data:
