services:
  sisgea-module-autorizacao:
    image: node:18
    user: node
    command: sh -c "tail -f /dev/null"
    container_name: sisgea-module-autorizacao
    working_dir: /sisgea/env-dev/modules/back-end/module-autorizacao
    depends_on:
      - sisgea-module-autorizacao-db
    networks:
      - sisgea-net
    ports:
      - 127.128.30.13:3013:3013
      - 127.128.30.13:9229:9229
    volumes:
      - ../../../../../libs:/sisgea/env-dev/libs
      - ../../:/sisgea/env-dev/modules/back-end/module-autorizacao
    env_file:
      - .env

  sisgea-module-autorizacao-db:
    image: bitnami/postgresql:15
    container_name: sisgea-module-autorizacao-db
    volumes:
      - 'sisgea-module-autorizacao-db-data:/bitnami/postgresql'
    networks:
      - sisgea-net
    ports:
      - 127.128.30.13:5432:5432
    env_file:
      - .db.env

networks:
  sisgea-net:
    external: true

volumes:
  sisgea-module-autorizacao-db-data:
